name = "Terra"
uuid = "cfcdd479-6883-4e94-b5c8-0a25d121abce"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DocStringExtensions = "0.9"
Rasters = "0.8"
Reexport = "1.2"
